// Mocks generated by Mockito 5.4.4 from annotations
// in mapnrank/test/repositories/user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:mapnrank/app/models/event_model.dart' as _i10;
import 'package:mapnrank/app/models/feedback_model.dart' as _i8;
import 'package:mapnrank/app/models/notification_model.dart' as _i11;
import 'package:mapnrank/app/models/post_model.dart' as _i9;
import 'package:mapnrank/app/models/user_model.dart' as _i7;
import 'package:mapnrank/app/providers/laravel_provider.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOptions_1 extends _i1.SmartFake implements _i2.Options {
  _FakeOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLaravelApiClient_3 extends _i1.SmartFake
    implements _i4.LaravelApiClient {
  _FakeLaravelApiClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LaravelApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockLaravelApiClient extends _i1.Mock implements _i4.LaravelApiClient {
  MockLaravelApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Dio);

  @override
  set httpClient(_i2.Dio? _httpClient) => super.noSuchMethod(
        Invocation.setter(
          #httpClient,
          _httpClient,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          _baseUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Options get optionsNetwork => (super.noSuchMethod(
        Invocation.getter(#optionsNetwork),
        returnValue: _FakeOptions_1(
          this,
          Invocation.getter(#optionsNetwork),
        ),
      ) as _i2.Options);

  @override
  set optionsNetwork(_i2.Options? _optionsNetwork) => super.noSuchMethod(
        Invocation.setter(
          #optionsNetwork,
          _optionsNetwork,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Options get optionsCache => (super.noSuchMethod(
        Invocation.getter(#optionsCache),
        returnValue: _FakeOptions_1(
          this,
          Invocation.getter(#optionsCache),
        ),
      ) as _i2.Options);

  @override
  set optionsCache(_i2.Options? _optionsCache) => super.noSuchMethod(
        Invocation.setter(
          #optionsCache,
          _optionsCache,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i4.LaravelApiClient> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue:
            _i6.Future<_i4.LaravelApiClient>.value(_FakeLaravelApiClient_3(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i6.Future<_i4.LaravelApiClient>);

  @override
  dynamic register(_i7.UserModel? user) => super.noSuchMethod(Invocation.method(
        #register,
        [user],
      ));

  @override
  dynamic registerInstitution(_i7.UserModel? user) =>
      super.noSuchMethod(Invocation.method(
        #registerInstitution,
        [user],
      ));

  @override
  dynamic getAnotherUserProfileInfo(int? userId) =>
      super.noSuchMethod(Invocation.method(
        #getAnotherUserProfileInfo,
        [userId],
      ));

  @override
  dynamic updateUser(_i7.UserModel? user) =>
      super.noSuchMethod(Invocation.method(
        #updateUser,
        [user],
      ));

  @override
  dynamic login(_i7.UserModel? user) => super.noSuchMethod(Invocation.method(
        #login,
        [user],
      ));

  @override
  _i6.Future<dynamic> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> checkTokenValidity(String? token) => (super.noSuchMethod(
        Invocation.method(
          #checkTokenValidity,
          [token],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> followUser(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [userId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> unfollowUser(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [userId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  dynamic sendFeedback(_i8.FeedbackModel? feedbackModel) =>
      super.noSuchMethod(Invocation.method(
        #sendFeedback,
        [feedbackModel],
      ));

  @override
  _i6.Future<dynamic> getAllZones(
    int? levelId,
    int? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllZones,
          [
            levelId,
            parentId,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getAllZonesFilterByName() => (super.noSuchMethod(
        Invocation.method(
          #getAllZonesFilterByName,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getSpecificZoneByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecificZoneByName,
          [name],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  dynamic getSpecificZoneGeoJson(String? url) =>
      super.noSuchMethod(Invocation.method(
        #getSpecificZoneGeoJson,
        [url],
      ));

  @override
  _i6.Future<dynamic> getSpecificZone(int? zoneId) => (super.noSuchMethod(
        Invocation.method(
          #getSpecificZone,
          [zoneId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getDisasterMarkers() => (super.noSuchMethod(
        Invocation.method(
          #getDisasterMarkers,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getAllSectors() => (super.noSuchMethod(
        Invocation.method(
          #getAllSectors,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getAllPosts(int? page) => (super.noSuchMethod(
        Invocation.method(
          #getAllPosts,
          [page],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getPostsByZone(int? zone_id) => (super.noSuchMethod(
        Invocation.method(
          #getPostsByZone,
          [zone_id],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> createPost(_i9.Post? post) => (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [post],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> updatePost(_i9.Post? post) => (super.noSuchMethod(
        Invocation.method(
          #updatePost,
          [post],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> likeUnlikePost(int? postId) => (super.noSuchMethod(
        Invocation.method(
          #likeUnlikePost,
          [postId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getAPost(int? postId) => (super.noSuchMethod(
        Invocation.method(
          #getAPost,
          [postId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> commentPost(
    int? postId,
    String? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #commentPost,
          [
            postId,
            comment,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  dynamic sharePost(int? postId) => super.noSuchMethod(Invocation.method(
        #sharePost,
        [postId],
      ));

  @override
  dynamic deletePost(int? postId) => super.noSuchMethod(Invocation.method(
        #deletePost,
        [postId],
      ));

  @override
  _i6.Future<dynamic> filterPostsByZone(
    int? page,
    int? zoneId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterPostsByZone,
          [
            page,
            zoneId,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> filterPostsBySectors(
    int? page,
    dynamic sectors,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterPostsBySectors,
          [
            page,
            sectors,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  dynamic getAllEvents(int? page) => super.noSuchMethod(Invocation.method(
        #getAllEvents,
        [page],
      ));

  @override
  _i6.Future<dynamic> getAnEvent(int? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getAnEvent,
          [eventId],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  dynamic createEvent(_i10.Event? event) =>
      super.noSuchMethod(Invocation.method(
        #createEvent,
        [event],
      ));

  @override
  dynamic updateEvent(_i10.Event? event) =>
      super.noSuchMethod(Invocation.method(
        #updateEvent,
        [event],
      ));

  @override
  dynamic deleteEvent(int? eventId) => super.noSuchMethod(Invocation.method(
        #deleteEvent,
        [eventId],
      ));

  @override
  _i6.Future<dynamic> filterEventsByZone(
    int? page,
    int? zoneId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterEventsByZone,
          [
            page,
            zoneId,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> filterEventsBySectors(
    int? page,
    dynamic sectors,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterEventsBySectors,
          [
            page,
            sectors,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getUserNotifications() => (super.noSuchMethod(
        Invocation.method(
          #getUserNotifications,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> getSpecificNotification(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecificNotification,
          [id],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> deleteSpecificNotification(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSpecificNotification,
          [id],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  dynamic createNotification(_i11.NotificationModel? notification) =>
      super.noSuchMethod(Invocation.method(
        #createNotification,
        [notification],
      ));

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
